# This is a basic workflow to help you get started with Actions

name: RSS

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # 每 1 小时运行一次
    # - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone the Project
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x # optional

      # Runs a set of commands using the runners shell
      - name: Install & Commit
        run: |
          export TZ='Asia/Shanghai'
          git config --global user.email "icolabot@e.yfun.top"
          git config --global user.name "iColaBot"
          npm i --save
          node index.js
          cd src/
          echo "rss.yfun.top" > CNAME
          #git init
          #git add -A
          #git commit -m "Update RSS"
          
      - name: Push
        run: |
          #git remote add origin https://github.com/yfun-lab/RSS.git
          #git push origin gh-pages -f
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./src
